name: Call Common Workflow
on:
  push:
    branches:
      - 'feature/**'
      - 'main'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  call-reusable:
    uses: ./.github/workflows/common_wf.yml
    with:
      branch-name: ${{ github.ref_name }}
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
