name: Call Common Workflow
on:
  push:
    branches:
      - 'feature/**'
      - 'main'
  merge_group:

jobs:
  call-common:
    uses: ./.github/workflows/common-build.yml
    with:
      branch-name: ${{ github.ref_name }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
