name: CI Pipeline (Using Reusable Workflow)

on:
  push:
    branches:
      - 'feature/**'
      - 'main'

jobs:
  call-reusable:
    uses: ./.github/workflows/java-build.yml
    with:
      java-version: '17'
      project-key: 'hello'
      sonar-org: 'sun-org'
      image-name: 'sunidhidocker/semtech-poc'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
