name: App Deployment
on:
  push:
    branches:
      - 'feature/**'
      - 'main'

env:
  IMAGE_NAME: sunidhidocker/semtech-poc

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          java-version: '11'
      - name: Compile and Package with Maven
        run: mvn clean package -DskipTests
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract Branch Name
        id: extract_branch
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.extract_branch.outputs.branch }} .
      - name: Push Docker Image to Docker Hub
        run: |
          docker push $IMAGE_NAME:${{ steps.extract_branch.outputs.branch }}

