name: Call Common Workflow
on:
  push:
    branches:
      - 'feature/**'
      - 'main'
  merge_group:

jobs:
  call-reusable:
    uses: ./.github/workflows/common-build.yml
    with:
      branch-name: ${{ github.ref_name }}
