name: Reusable Java Build

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      project-key:
        required: false
        type: string
      sonar-org:
        required: false
        type: string
      image-name:
        required: true
    secrets:
      SONAR_TOKEN:
        required: false
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

env:
  IMAGE_NAME: ${{ inputs.image-name }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'

      - name: Compile and Package with Maven
        run: mvn clean verify package -DskipTests

      - name: Optional SonarCloud Scan
        if: ${{ secrets.SONAR_TOKEN != '' }}
        run: mvn verify sonar:sonar \
          -Dsonar.projectKey=${{ inputs.project-key }} \
          -Dsonar.organization=${{ inputs.sonar-org }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract Branch Name
        id: extract_branch
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.extract_branch.outputs.branch }} .
      - name: Push Docker Image to Docker Hub
        run: |
          docker push $IMAGE_NAME:${{ steps.extract_branch.outputs.branch }}
